name: run bs_news.py
'on':
  push:
    paths:
      - BS_news.py
      - BT_news.py
      - Nse_data.py

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        env:
          PYTHONUNBUFFERED: '1'
          FORWARDER_API_KEY: '${{ secrets.FORWARDER_API_KEY }}'
          METRICS_GROUP_ID: '${{ secrets.METRICS_GROUP_ID }}'
          METRICS_CHANNEL_ID: '${{ secrets.METRICS_CHANNEL_ID }}'
        run: python forwarder.py
      - name: commit files
        run: >
          git config --local user.email "action@github.com"

          git config --local user.name "GitHub Action"

          git add -A

          git diff-index --quiet HEAD || (git commit -a -m "updated logs"
          --allow-empty)
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
