name: OpenInterest Extractor
'on':
  workflow_dispatch: null
  schedule:
    - cron: '30 4 * * mon-fri'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r OI_requirements.txt
      - name: execute py script
        env:
          PYTHONUNBUFFERED: "1"
          API_KEY: '${{ secrets.API_KEY }}'
          GROUP_ID: '${{ secrets.METRICS_CHANNEL_ID }}'
          OI_USERNAME: '${{ secrets.OI_USERNAME }}'
          OI_PASSWORD: '${{ secrets.OI_PASSWORD }}'
        run: python OpenInterest.py
      - name: forward messages
        env:
          PYTHONUNBUFFERED: "1"
          FORWARDER_API_KEY: '${{ secrets.FORWARDER_API_KEY }}'
          METRICS_GROUP_ID:  '${{ secrets.METRICS_GROUP_ID }}'
          METRICS_CHANNEL_ID:  '${{ secrets.METRICS_CHANNEL_ID }}'
        run: python forwarder.py
      - name: commit files
        run: >
          git config --local user.email "action@github.com"

          git config --local user.name "GitHub Action"

          git add -A

          git diff-index --quiet HEAD || (git commit -a -m "updated logs"
          --allow-empty)
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
