name: run bs_news.py
'on':
  workflow_dispatch: null
  schedule:
    - cron: 0 3-13 * * mon-fri
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        env:
          PYTHONUNBUFFERED: '1'
          API_KEY: '${{ secrets.API_KEY }}'
          GROUP_ID: '${{ secrets.GROUP_ID }}'
        run: python BS_news.py
