name: run test.py
'on':
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
      - name: execute py script
        env:
          PYTHONUNBUFFERED: "1"
          TEST_ARRAY: '${{ secrets.TEST_ARRAY }}'
        run: python test.py
      
